services:
  database:
    container_name: tetrips-db-container
    image: mysql:8.0.22
    volumes:
      - ~/docker/mysql/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - ~/docker/mysql/var/lib/mysql:/var/lib/mysql
      - ~/docker/mysql/var/log/mysql:/var/log/mysql
    environment:
      - MYSQL_DATABASE=tetripsdb
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=%
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3306:3306"
    networks:
      - test_env
  application:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://tetrips-db-container:3306/tetripsdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - test_env
networks:
  test_env:
    driver: bridge